steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/argo-${_ENV}-rentsoft-ms-communication-php-fpm-api:latest || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/argo-${_ENV}-rentsoft-api-gateway-krakend:$SHORT_SHA',
        '-t', 'gcr.io/$PROJECT_ID/argo-${_ENV}-rentsoft-api-gateway-krakend:latest',
        '--cache-from', 'gcr.io/$PROJECT_ID/argo-${_ENV}-rentsoft-ms-communication-php-fpm-api:latest',
        '-f', './Dockerfile-${_ENV}',
        '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        docker push gcr.io/$PROJECT_ID/argo-${_ENV}-rentsoft-api-gateway-krakend:$SHORT_SHA
        docker push gcr.io/$PROJECT_ID/argo-${_ENV}-rentsoft-api-gateway-krakend:latest

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    secretEnv: ['GIT_ACCESS_TOKEN']
    args:
      - '-c'
      - |
        git clone https://mvnrs:$$GIT_ACCESS_TOKEN@github.com/MVnRs/rentsoft_api_gateway_krakend-deployment.git ${_ENV}-rentsoft_api_gateway_krakend-deployment -b ${_CD_BRANCH}
        echo "Updating image tag version ..."
        cd ${_ENV}-rentsoft_api_gateway_krakend-deployment
        sed "s/GOOGLE_CLOUD_PROJECT/$PROJECT_ID/g" ${_ENV}/deployment.yaml.tpl | \
        sed "s/COMMIT_SHA/${SHORT_SHA}/g" > ${_ENV}/deployment.yaml
        echo "Pushing changes to k8s manifest repo ..."
        git config --global user.name "Automatic build"
        git config --global user.email "dev@rentsoft.de"
        git add -A
        git commit -m "[Cloud Builder] Updated image tag $SHORT_SHA from commit ${COMMIT_SHA}."
        git push https://mvnrs:$$GIT_ACCESS_TOKEN@github.com/MVnRs/rentsoft_api_gateway_krakend-deployment.git ${_CD_BRANCH}

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 2400s

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/github-access-token/versions/latest
      env: 'GIT_ACCESS_TOKEN'
