FROM devopsfaith/krakend:2.0.0 as krakend

COPY krakend/krakend.json /etc/krakend/krakend.json
COPY krakend/entrypoint.sh /etc/krakend/entrypoint.sh

WORKDIR /etc/krakend/partials
COPY krakend/partials/prod/auth_keycloak.tmpl /etc/krakend/partials/auth_keycloak.tmpl

WORKDIR /etc/krakend/settings
COPY krakend/settings/prod/endpoint.json /etc/krakend/settings/endpoint.json
COPY krakend/settings/prod/service.json /etc/krakend/settings/service.json

ENV FC_ENABLE=1
ENV FC_SETTINGS="/etc/krakend/settings"
ENV FC_PARTIALS="/etc/krakend/partials"
#ENV FC_OUT="/tmp/krakend_out.json"

#ENTRYPOINT ["bash", "entrypoint.sh" ]