FROM devopsfaith/krakend:2.0.0 as krakend

ARG ENV

ENV FC_ENABLE=1
ENV FC_SETTINGS="/etc/krakend/settings/dev"
ENV FC_PARTIALS="/etc/krakend/partials/dev"
#ENV FC_OUT="/etc/krakend/out.json"

#ENTRYPOINT ["/bin/sh", "entrypoint.sh" ]